version: '3.8'

services:
  php:
    build: .
    container_name: yii_project_php
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: php -S 0.0.0.0:8080 -t public
    ports:
      - "8080:8080"
    environment:
      - DB_DSN=mysql:host=db;dbname=php
      - DB_USER=root
      - DB_PASS=root
    depends_on:
      - db  # Говорим, что PHP должен ждать MySQL

  db:
    image: mysql:8
    container_name: yii_project_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: php_oop_crud_level_1
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
